site_name: nps-fm-2020
site_description: Python package to estimate the grades for the nps-fm-2020

repo_url: https://github.com/nps-fm-2020
repo_name: nps-fm-2020

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue grey
          accent: light green
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue grey
          accent: light green
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - npsfm

nav:
    - About: index.md
    - Reference:
        - npsfm: reference/npsfm.md
